### ISSUE TITLE
Incorrect test module name in test.html

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/generator-donejs#123]
The test.html page generates with:

```
main="test/test"
```

Should be:

```
main=“<package-name>/test"
```

**Comment by phillipskevin** [comment]
Is this an issue with the plugin generator? It looks like that creates a test.html with `main="test/test"`. The app generator is working fine for me.

**Comment by phillipskevin** [comment]
Also, the plugin generator won't work with `main=“<package-name>/test/"` because directories.lib is set to src, so it tries to resolve to `<package-name>/src/test/test.js`

**Comment by justinbmeyer** [comment]
@phillipskevin yeah, then test.js should be in `src/test/test.js`.

**Comment by phillipskevin** [comment]
Going to prioritize getting the basic app generator working and making sure there is a path for existing projects to upgrade to 1.0 before working on this.

**Comment by matthewp** [comment]
This is no longer happening.

**Comment by matthewp** [comment]
I was probably thinking of the app generator.

**Comment by phillipskevin** [comment]
Ok, I'll make the changes to the plugin generator then.

**Comment by phillipskevin** [comment]
Here is the plan for making this change:

**Plugin generator changes:**
- [ ] remove `test` folder
- [ ] move test.html directly into root folder
- [ ] make `"main"` in test.html the `<%= name %>_test.js` file

**App generator changes:**
- [ ] move test.html directly into root folder
- [ ] move test.js into `src/`
- [ ] move functional tests into `src/test.js`
- [ ] remove `src/test/functional.js`

**module generator changes:**
- [ ] add `import` statement to `src/test.js` instead of `src/test/test.js`

**component generator changes:**
- [ ] add `import` statement to `src/test.js` instead of `src/test/test.js`

**supermodel generator changes:**
- [ ] add `import` statement to `src/test.js` instead of `src/test/test.js`

**Comment by phillipskevin** [comment]
Also need to
- [ ] update the guides
