### ISSUE TITLE
Fix plugin version script to include dist folder

### ISSUE THREAD

**Issue by chasenlehara** [donejs/generator-donejs#202]
When a plugin is published to npm, it doesn’t include the `dist` folder.

Here’s the `version` script: https://github.com/donejs/generator-donejs/blob/a50d2851bf788ec11473b49e9c8b46a1eff4bd82/plugin/index.js#L120

The issue is that the `dist` folder is added in a commit to the `release` branch, then it switches to `master` before `npm publish` is run, which means the `dist` folder is no longer there for it to be published to npm.

Here’s a commit that shows a potential fix: https://github.com/chasenlehara/chasen-number-input/commit/a08957f392eaeb46a25303b84151b3ccebaf52d8

That commit changes `postversion` to `postpublish` so it’s still on the `release` branch when publishing to npm. It also changes the commit message that includes the version bump.

Ideally, the version bump commit message would have the version number in it, but I haven’t figured out a way to do that without creating a script.

**Comment by phillipskevin** [comment]
I think this change makes sense.

Another option is what we're doing on canjs/canjs, which runs the build during each of the `release` scripts: https://github.com/canjs/canjs/blob/master/package.json#L16-L19.

I think changing to `postpublish` is a better solution though since you only have to do it in one place.
